Term = {
      AppTerm
    | IfThenElse
}

AppTerm = {
      ATerm
    | Succ
    | Pred
    | IsZero
}

ATerm = {
      True
    | False
    | Zero
    | "(" ~ Term ~ ")"
}

True = { "true" }
False = { "false" }
IfThenElse = { "if" ~ Term ~ "then" ~ Term ~ "else" ~ Term }
Zero = { "0" }
Succ = { "succ" ~ ATerm }
Pred = { "pred" ~ ATerm }
IsZero = { "iszero" ~ ATerm }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
